version: '3'

dotenv: ['.env']

includes:
  os:
    taskfile: Taskfile_{{OS}}.yml
    vars:
      TARGET: "./_run"

tasks:
  build:
    cmds:
      - go build -o sociomile ./cmd/main.go
  migrate:
    cmds:
      - docker exec -it sociomile-mysql /bin/bash -c 'mysql -uroot -p{{.MYSQL_ROOT_PASSWORD}} < /usr/share/queries/dbuser.sql'

  start-containers:
    cmds:
      - mkdir -p ./_run/mysql
      - docker-compose up -d --wait
      - task: migrate
  stop:
    cmds:
      - docker-compose down
  clean:
    cmds:
      - docker-compose down --volumes --remove-orphans
      - task: os:remove-rundir
  reinit:
    cmds:
      - task: clean
      - task: start-containers
  
  default: 
    cmds:
      - ls .env
      - task: start-containers