version: '3'

dotenv: ['.env']

includes:
  os:
    taskfile: Taskfile_{{OS}}.yml

tasks:
  build:
    cmds:
      - go build -o sociomile ./cmd/main.go

  migrate:
    cmds:
      - docker exec -it sociomile-mysql /bin/bash -c "sed 's/<database_name>/{{.MYSQL_DATABASE}}/g' /usr/share/queries/init.sql | mysql -uroot -p{{.MYSQL_ROOT_PASSWORD}}"
      - goose up

  start-containers:
    cmds:
      - mkdir -p ./_run/mysql
      - docker-compose up -d --wait
      - task: migrate

  run-tests:
    cmds:
      - go test ./... | grep -v '?'

  stop:
    cmds:
      - docker-compose down

  clean:
    cmds:
      - docker-compose down --volumes --remove-orphans
      - task: os:remove-rundir
        vars:
          TARGET: "./_run"

  reinit:
    cmds:
      - task: clean
      - task: start-containers
  
  default: 
    cmds:
      - ls .env
      - goose -version
      - task: start-containers
      # - task: run-tests