version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - go build -o sociomile ./cmd/main.go

  migrate:
    cmds:
      - docker exec -it sociomile-mysql /bin/bash -c "sed 's/<database_name>/{{.MYSQL_DATABASE}}/g' /usr/share/queries/init.sql | mysql -uroot -p{{.MYSQL_ROOT_PASSWORD}}"
      - goose up

  start:
    cmds:
      - ls .env
      - goose -version
      - task: start-containers

  start-containers:
    cmds:
      - mkdir -p ./_run/mysql
      - mkdir -p ./_run/rabbitmq
      - docker-compose up -d --wait
      - task: migrate
  
  stop:
    cmds:
      - docker-compose down

  clean:
    cmds:
      - docker-compose down --volumes --remove-orphans
      - docker exec -it sociomile-mysql mysql -uroot -p{{.MYSQL_ROOT_PASSWORD}} -e "DROP DATABASE IF EXISTS {{.MYSQL_DATABASE}}; CREATE DATABASE {{.MYSQL_DATABASE}};"
      - task: start-containers

  test:
    cmds:
      - go test -count=1 ./... | grep -v '?'
  
  default: 
    cmds:
      - task: start
